### ISSUE TITLE
Cygwin ENOENT error

### ISSUE THREAD

**Issue by aliosv** [tarmolov/git-hooks-js#1]
https://github.com/tarmolov/git-hooks-js/blob/master/lib/git-hooks.js#L131
````Error: spawn P:\some-project\.githooks\pre-commit\lint ENOENT````

result of executing in terminal ````P:\some-project\.githooks\pre-commit\lint```` - "bash: command not found"
````bash P:\some-project\.githooks\pre-commit\lint```` - works

i.e. with such code modifying all works ````var hook = spawn('bash', [hooks.shift()], {stdio: 'inherit'});````

**Comment by tarmolov** [comment]
Could you try [win-spawn](https://github.com/ForbesLindesay/win-spawn) instead of spawn?
```javascript
spawn = require('win-spawn');
var hook = spawn(hooks.shift(), args, {stdio: 'inherit'});
```

**Comment by aliosv** [comment]
````:\some-project\.githooks\pre-commit\lint не является внутренней или внешней командой, исполняемой программой или пакетным файлом.````

**Comment by tarmolov** [comment]
:disappointed: 
Ok. I'm going to install windows on a virtual machine and try to find a solution.

**Comment by tarmolov** [comment]
It usually means there's a ^M (carriage return) at the end of each line of your file or some other encoding issue which prevents the #!/bin/bash line being interpreted correctly.

http://superuser.com/questions/484041/run-shell-script-on-windows-using-cygwin

**Comment by tarmolov** [comment]
Does it work for you?

**Comment by tarmolov** [comment]
Close the issue. If you still reproduce the problem, please feel free to reopen.

**Comment by aliosv** [comment]
> Does it work for you?
No. In your VM?

**Comment by tarmolov** [comment]
I couldn't launch an image from modern.ie. 
Some weird errors have occurred which stopped an appliance import :-/
