### ISSUE TITLE
Remove all dependencies

### ISSUE THREAD

**Issue by tarmolov** [tarmolov/git-hooks-js#2]
`git-hooks` [postinstall script fails from time to time because of missing dependency](https://github.com/npm/npm/issues/8850).
The issues is fixed in `npm@3` but the majority of clients use `npm@2`.

**Comment by tarmolov** [comment]
@ikokostya, when you remove `vow` and `vow-fs`, please remove `commander` as well.

**Comment by zloylos** [comment]
Completed
