### ISSUE TITLE
[GIT-HOOKS ERROR] Incorrect value of args option

### ISSUE THREAD

**Issue by marcelloromanelli** [tarmolov/git-hooks-js#27]
Since I've upgraded to `1.1.6` I'm getting the following error

```
[GIT-HOOKS ERROR] Incorrect value of args option
```

I've downgraded to `1.1.5` and everything is back to normal.

**Comment by tarmolov** [comment]
It seems that you hit a npm bug.
See https://github.com/tarmolov/git-hooks-js/issues/22#issuecomment-246307819. It should help to fix it.

Please try and let me know if it doesn't help.

**Comment by zakhenry** [comment]
Thanks @tarmolov your suggestion helped. To be precise, running `npm install git-hooks` again prompts the postinstall process which cleared whatever had gone wrong in the interim
