### ISSUE TITLE
Simplify configuration

### ISSUE THREAD

**Issue by alt-j** [tarmolov/git-hooks-js#8]
In my opinion, [precommit-hook](https://www.npmjs.com/package/precommit-hook) config more usefull, and we can transfer all configuration to package.json too. For example, it can looks like that:
```json
"hooks": {
    "pre-commit": [
        {
            "test": "/*\.js$/",
            "script": ["lint", "test"]
        },
        {
            "test": "/*\.css$/",
            "script": ["csscomb"]
        },
        ...
    ]
}
```

@tarmolov, what do you think about that?

**Comment by arrowrowe** [comment]
```js
"hooks": {
  "pre-commit": [
    "eslint .",
    "jshint ."
  ],
  "post-merge": "gulp build"  // equivalent to ["gulp build"]
}
```

Maybe this way?...

**Comment by alt-j** [comment]
We can support four options:

- Simplest
```json
"eslint . && jshint ."
```
- Usual
```json
[
    "eslint .",
    "jshint ."
]
```
- Advanced (for speed optimization)
```json
[
        {
            "test": "/\.js$/",
            "script": ["lint", "test"]
        },
        {
            "test": "/\.css$/",
            "script": ["csscomb"]
        }
]
```
- Mix
```json
[
        {
            "test": "/\.js$/",
            "script": ["lint", "test"]
        },
        "test"
]
```

**Comment by tarmolov** [comment]
I want to keep the current way of running git hooks (from `.githooks` directory).
if `git-hook` has two ways to specify hooks, it'll look a little bit weird for me.

IMHO, it's better to make a pr to [ghooks](https://github.com/gtramontina/ghooks) to support this feature.
